services:
  # --- DATABASES ---
  # For local volume dockerized testing
  # user-db-mongodb:
  #   image: mongo
  #   container_name: user-db-mongodb
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./user-service/db:/data/db
  #   networks:
  #     - app-network

  # For local volume dokcerized development purposes
  # user-db-mongo-express:
  #   image: mongo-express
  #   container_name: user-db-mongo-express
  #   restart: unless-stopped
  #   ports:
  #     - 8084:8081
  #   env_file:
  #     - .env
  #   networks:
  #     - app-network
  #   depends_on:
  #     - user-db-mongodb

  question-db-pg:
    image: postgres:14-alpine
    container_name: question-db-pg
    ports:
      - '5433:5432'
    volumes:
      - question-data:/var/lib/postgresql/data
      - ./question-service/db:/docker-entrypoint-initdb.d
      - ./history-service/db/init.sql:/docker-entrypoint-initdb.d/2-history-init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: question-db
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - app-network

  # --- FRONTEND ---
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:5173'
    environment:
      - NODE_ENV=development
      - VITE_NGROK_COLLAB_HOST=${VITE_NGROK_COLLAB_HOST}
      - VITE_HISTORY_SERVICE_URL=http://localhost:8085
      - VITE_QUESTION_SERVICE_URL=http://localhost:8083
      - VITE_USER_SERVICE_URL=http://localhost:8080
      - VITE_MATCHING_SERVICE_URL=http://localhost:8081
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - user-service
      - question-service
      - matching-service
      - collaboration-service
    networks:
      - app-network

  # --- BACKEND ---
  # User service
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development
      - PORT=8080
    env_file:
      - ./.env
    volumes:
      - ./user-service:/app
      - /app/node_modules
    networks:
      - app-network
    # depends_on: # Uncomment if local volume
    #   - user-db-mongodb
    command: sh -c "npm run seed:admin || true && npm run dev" # for production change to npm start

  # Question service
  question-service:
    build:
      context: ./question-service
      dockerfile: Dockerfile
    ports:
      - '8083:8083'
    environment:
      - NODE_ENV=production
      - PORT=8083
    env_file:
      - ./.env
    depends_on:
      - question-db-pg
    volumes:
      - ./question-service:/app
      - /app/node_modules
    networks:
      - app-network

  question-test:
    build:
      context: ./question-service
      dockerfile: Dockerfile
    command: ['npm', 'test']
    env_file:
      - ./question-service/.env.test
    depends_on:
      question-db-pg:
        condition: service_healthy
    networks:
      - app-network

  # --- UI for Postgres Database ---
  adminer:
    image: adminer
    container_name: adminer-ui
    restart: unless-stopped
    ports:
      - '8087:8080'
    networks:
      - app-network
    depends_on:
      - question-db-pg

  # Matching service
  matching-service:
    # ... (No changes needed)
    build:
      context: ./matching-service
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    environment:
      - NODE_ENV=development
      - PORT=8081
    env_file:
      - ./.env
    volumes:
      - ./matching-service:/app
      - /app/node_modules
    networks:
      - app-network

  # Collaboration service
  collaboration-service:
    build:
      context: ./collaboration-service
      dockerfile: Dockerfile
    ports:
      - '8082:8082'
    environment:
      - NODE_ENV=development
      - PORT=8082
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - USER_SERVICE_URL=${USER_SERVICE_URL}
    env_file:
      - ./.env
    volumes:
      - ./collaboration-service:/app
      - /app/node_modules
      - /app/.partykit
    networks:
      - app-network

  # History service
  history-service:
    build:
      context: ./history-service
      dockerfile: Dockerfile
    ports:
      - '8085:8085'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@question-db-pg:5432/question-db
      - PORT=8085
    env_file:
      - ./.env
    depends_on:
      #   - user-db-mongodb # Uncomment if local volume
      question-db-pg:
        condition: service_healthy # Wait for DB to be ready
    volumes:
      - ./history-service:/app
      - /app/node_modules
    networks:
      - app-network
    command: npm run dev

  code-execution-service:
    build:
      context: ./code-execution-service
      dockerfile: Dockerfile
    ports:
      - '8086:8086'
    environment:
      - PORT=8086
    env_file:
      - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/code-execution:/tmp/code-execution
      - ./code-execution-service:/app
      - /app/node_modules
    networks:
      - app-network
    command: npm run dev

networks:
  app-network:
    driver: bridge

volumes:
  question-data:
